openapi: "3.0.0"

info:
  version: 0.0.1
  title: Person Service API

paths:
  /v1/ping/pong:
    post:
      summary: Checks to see if the API GW and Lambda is up.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                control:
                  type: object
                data:
                  type: object
              example:
                control: {}
                data: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: string
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f1a8207b-a1e5-4ef4-8425-9ecaa7e1a457"
                  data: "Pong"

  /v1/client/create:
    post:
      summary: Creates a client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                control:
                  type: object
                data:
                  type: object
                  properties:
                    name:
                      type: string
              example:
                control: {}
                data:
                  name: "AWESOME CLIENT"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    $ref: "#/components/schemas/Client"
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data:
                    client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                    name: "AWESOME CLIENT"
                    person_count: 0
                    created_at: "2020-06-25 17:59:10.961"

  /v1/client/find_first:
    post:
      summary: Finds the first X amount of clients
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                control:
                  type: object
                data:
                  type: object
                  properties:
                    limit:
                      type: number
              example:
                control: {}
                data:
                  limit: 100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: object
                    properties:
                      Items:
                        type: array
                        items:
                          $ref: "#/components/schemas/Client"
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data:
                    - client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                      name: "AWESOME CLIENT"
                      person_count: 0
                      created_at: "2020-06-25 17:59:10.961"

  /v1/client/find:
    post:
      summary: Finds a specific client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                control:
                  type: object
                data:
                  type: object
                  properties:
                    client_id:
                      type: string
              example:
                control: {}
                data:
                  client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    $ref: "#/components/schemas/Client"
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data:
                    client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
                    name: "AWESOME CLIENT"
                    person_count: 0
                    created_at: "2020-06-25 17:59:10.961"

  /v1/client/increment_person_count:
    post:
      summary: Increments the person count for a specific client
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                control:
                  type: object
                data:
                  type: object
                  properties:
                    client_id:
                      type: string
              example:
                control: {}
                data:
                  client_id: "94a72d65-b27e-4a84-be46-1bdc237f7a8f"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  control:
                    type: object
                    properties:
                      ResponseCode:
                        type: number
                      TraceID:
                        type: string
                  data:
                    type: boolean
                example:
                  control:
                    ResponseCode: 2000
                    TraceID: "f3a04797-8d56-4604-ad10-933feccf7015"
                  data: true

components:
  schemas:
    Client:
      type: object
      properties:
        client_id:
          type: string
        name:
          type: string
        person_count:
          type: number
        created_at:
          type: string